---
- name: munge is restarted
  service: name=munge state=restarted

- name: slurmctld is restarted
  service: name=slurmctld state=restarted

- name: rsyslog is restarted
  service: name=rsyslog state=restarted
