---
- name: install ganglia packages
  yum: name={{ item }} state=present
  with_items:
  - ganglia-devel
  - ganglia-gmetad
  - ganglia-web

- name: ensure /var/lib/ganglia/rrds is owned by nobody
  file:
    path: "/var/lib/ganglia/rrds"
    owner: "nobody"

- name: gmetad is configured
  template: src="gmetad.conf" dest="/etc/ganglia/gmetad.conf"
  notify:
  - gmetad is restarted

- name: gmetad is enabled and running
  service: name=gmetad state=started enabled=yes

- name: httpd is enabled and running for the web interface
  when: enable_web_interface
  service: name=httpd state=started enabled=yes

- name: ensure /var/lib/ganglia/dwoo/ is writable by web interface
  when: enable_web_interface
  file: path=/var/lib/ganglia/dwoo group=apache mode=0775

- name: ensure /var/lib/ganglia/dwoo/cache is writable by web interface
  when: enable_web_interface
  file: path=/var/lib/ganglia/dwoo/cache group=apache mode=0775

- name: ensure /var/lib/ganglia/dwoo/compiled is writable by web interface
  when: enable_web_interface
  file: path=/var/lib/ganglia/dwoo/compiled group=apache mode=0775

