---
- name: ensure nfs-related packages are installed
  yum: name={{item}} state=latest
  with_items:
  - lvm2
  - nfs-utils
  - nfs4-acl-tools

- name: configure exports
  template: src=exports dest=/etc/exports
  notify:
  - exportfs

- name: ensure rpcbind is running
  service: name=rpcbind state=started enabled=yes

- name: ensure nfs-server is running
  service: name=nfs-server state=started enabled=yes
